DEVICE     = atmega328p
CLOCK      = 16000000
OBJECTS    = main.o

MINIPRO    = minipro -p "ATMEGA328P@DIP28"
COMPILE    = avr-gcc -Wall -Os -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)

all: main.hex

.c.o:
	$(COMPILE) -c $< -o $@

.S.o:
	$(COMPILE) -x assembler-with-cpp -c $< -o $@

.c.s:
	$(COMPILE) -S $< -o $@

flash: all
	$(MINIPRO) -w main.hex -f ihex -s

fuse:
	$(MINIPRO) -w fuses.conf -c config

install: flash fuse

clean:
	rm -f main.hex main.elf $(OBJECTS)

main.elf: $(OBJECTS)
	$(COMPILE) -o main.elf $(OBJECTS)

main.hex: main.elf
	rm -f main.hex
	avr-objcopy -j .text -j .data -O ihex main.elf main.hex
	avr-size --format=avr --mcu=$(DEVICE) main.elf

disasm: main.elf
	avr-objdump -d main.elf

cpp:
	$(COMPILE) -E main.c
